insert Sega.Platform(Name, Manufacturer)
values 
(N'Astro City Mini', N'Sega'),
(N'Dreamcast', N'Sega'),
(N'Game Boy Advance', N'Nintendo'),
(N'Game Boy Color', N'Nintendo'),
(N'Game Gear Micro', N'Sega'),
(N'Gamecube', N'Nintendo'),
(N'Genesis Mini', N'Sega'),
(N'Microsoft Windows', N'Microsoft'),
(N'NeoGeo Pocket Color', N'SNK'),
(N'Nintendo 3DS', N'Nintendo'),
(N'Nintendo DS', N'Nintendo'),
(N'Nintendo Switch', N'Nintendo'),
(N'PlayStation 2', N'Sony'),
(N'PlayStation 3', N'Sony'),
(N'PlayStation 4', N'Sony'),
(N'PlayStation 5', N'Sony'),
(N'PlayStation Portable', N'Sony'),
(N'PlayStation Vita', N'Sony'),
(N'Stadia', N'Google'),
(N'Wii', N'Nintendo'),
(N'Wii U', N'Nintendo'),
(N'WonderSwan Color', N'Bandai'),
(N'Xbox', N'Microsoft'),
(N'Xbox 360', N'Microsoft'),
(N'Xbox One', N'Microsoft'),
(N'Xbox Series X', N'Microsoft')
